-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgso7evV5whSgYREvd
nuNHMkWKYu5+UGczeYtNrDtGaFmgCgYIKoZIzj0DAQehRANCAATxDXf7NhWFXPDl
lU0RE9agGU1tkIv6xAjZNRS2jc7nod6iEV6QQvyflwLWFr6gLnanBLAAiNMF5qIX
t4+JqMBg
-----END PRIVATE KEY-----